# This is a basic workflow to help you get started with Actions

name: Publish To VSCode [manual]

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Choose an branch to deploy'
        required: true
        default: 'master'
      version:
        description: 'Choose version bump types: major | minor | patch'
        required: true
        default: 'patch'
      dryRun:
        description: 'Set this option to true to package your extension but do not publish it.'
        required: true
        default: 'false' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: vscode

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          
      - uses: bahmutov/npm-install@v1

#       - name: Bump Version
#         run: |
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           npm version ${{ github.event.inputs.version }}

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          yarn: true
          dryRun: ${{ github.event.inputs.dryRun }}

#       - name: Push changes
#         uses: ad-m/github-push-action@v0.6.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.event.inputs.branch }}
